// <auto-generated />
namespace WallApp.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingtimeofcreationforpostsandcomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingtimeofcreationforpostsandcomments));
        
        string IMigrationMetadata.Id
        {
            get { return "201704011213404_Adding time of creation for posts and comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
